In [ ]:
import numpy as np
import pandas as pd
df = pd.read_csv(r"C:\Users\KHOO\Downloads\vessel_movements_PPT.csv")
df.tail(20)

In [2]:
df["vessel_type"].value_counts()

vessel_type
Container Ship (Fully Cellular)             847112
Tug                                         654754
Chemical/Products Tanker                    365898
Products Tanker                             354522
Bunkering Tanker                            149807
Asphalt/Bitumen Tanker                      100951
Landing Craft                                64949
Fishing Vessel                               46040
Vehicles Carrier                             31639
Water Tanker                                 28004
General Cargo Ship                           27493
Passenger Ship                               26598
Crude/Oil Products Tanker                    25828
Pusher Tug                                   16377
Anchor Handling Tug Supply                    9767
Cement Carrier                                8491
Utility Vessel                                6532
Open Hatch Cargo Ship                         6371
Anchor Handling Vessel                        6225
Bulk Carrier                                  6035
Crew/Supply Vessel                            4976
Platform Supply Ship                          4895
Offshore Support Vessel                       4604
Diving Support Vessel                         4554
Crude Oil Tanker                              4412
Deck Cargo Ship                               3302
Refrigerated Cargo Ship                       1798
Yacht                                         1774
Fish Carrier                                  1243
Heavy Load Carrier                            1208
Research Survey Vessel                         843
Chemical Tanker                                724
Cutter Suction Dredger                         698
Crane Vessel                                   697
Passenger/Cruise                               558
Drilling Rig, jack up                          541
Trailing Suction Hopper Dredger                447
Offshore Tug/Supply Ship                       374
Crane Vessel, non propelled                    295
Passenger/Ro-Ro Ship (Vehicles)                280
Ro-Ro Cargo Ship                               264
Cable Layer                                    143
LPG Tanker                                     138
Wood Chips Carrier                             105
Buoy Tender                                     98
Passenger/Landing Craft                         64
Aggregates Carrier                              43
Pipe Layer Crane Vessel                         30
Heavy Load Carrier, semi submersible            20
General Cargo Ship (with Ro-Ro facility)        18
Mooring Vessel                                  15
Work/Repair Vessel                              13
Waste Disposal Vessel                           11
LPG/Chemical Tanker                              8
Unknown                                          7
Livestock Carrier                                4
Hopper, Motor                                    2
Name: count, dtype: int64

In [8]:
l_1 = ["Container Ship (Fully Cellular)","Chemical/Products Tanker","Products Tanker","Bunkering Tanker","Asphalt/Bitumen Tanker","General Cargo Ship","Passenger Ship","Crude/Oil Products Tanker","Bulk Carrier","Crude Oil Tanker","Refrigerated Cargo Ship","Fish Carrier","Chemical Tanker","Passenger/Cruise","Passenger/Ro-Ro Ship (Vehicles)","Ro-Ro Cargo Ship","LPG Tanker","Buoy Tender","Passenger/Landing Craft","Aggregates Carrier","General Cargo Ship (with Ro-Ro facility)","LPG/Chemical Tanker"]

In [27]:
df["require"] = False
df.loc[df["vessel_type"].isin(l_1),"require"]=True
df

,imo,mmsi,vessel_id,vessel_name,date_of_build,vessel_type,group,timestamp,date_only,lon,...,terminal,maneuvering_zone,p,vref,sfc_me,sfc_ae,sfc_ab,ael,abl,require
0,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:01:42.000Z,2023-09-17,103.826065,...,NaN,NaN,7860.0,14.5,185.00,230.0,300.0,507.0,365.0,True
1,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:01:44.000Z,2023-09-17,103.826065,...,NaN,NaN,7860.0,14.5,185.00,230.0,300.0,507.0,365.0,True
2,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:07:43.000Z,2023-09-17,103.825690,...,NaN,NaN,7860.0,14.5,185.00,230.0,300.0,507.0,365.0,True
3,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:07:45.000Z,2023-09-17,103.825690,...,NaN,NaN,7860.0,14.5,185.00,230.0,300.0,507.0,365.0,True
4,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:10:42.000Z,2023-09-17,103.825580,...,NaN,NaN,7860.0,14.5,185.00,230.0,300.0,507.0,365.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2822594,9708693,374766000,714547,MSC CLARA,2015-11-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T21:59:17.000Z,2023-08-21,103.761665,...,NaN,PPT Maneouvering Zone,62500.0,19.0,175.00,220.0,300.0,NaN,NaN,True
2822595,9708693,374766000,714547,MSC CLARA,2015-11-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T22:02:17.000Z,2023-08-21,103.761665,...,NaN,PPT Maneouvering Zone,62500.0,19.0,175.00,220.0,300.0,4493.0,908.0,True
2822596,9449106,636020361,647347,MENDELSSOHN,2012-04-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T21:58:47.000Z,2023-08-21,103.783330,...,NaN,PPT Maneouvering Zone,31990.0,23.0,174.83,220.0,300.0,NaN,NaN,True
2822597,9449106,636020361,647347,MENDELSSOHN,2012-04-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T22:01:47.000Z,2023-08-21,103.783330,...,NaN,PPT Maneouvering Zone,31990.0,23.0,174.83,220.0,300.0,2503.0,436.0,True
2822598,9450313,636091832,647462,Northern Priority,2009-10-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T22:01:40.000Z,2023-08-21,103.766670,...,NaN,PPT Maneouvering Zone,36560.0,22.5,172.91,195.0,300.0,NaN,NaN,True

In [26]:
df.loc[df["require"]==False]

,imo,mmsi,vessel_id,vessel_name,date_of_build,vessel_type,group,timestamp,date_only,lon,...,terminal,maneuvering_zone,p,vref,sfc_me,sfc_ae,sfc_ab,ael,abl,require
674,9888754,563071620,755130,CLS SINGAPORE,2020-07-01,Utility Vessel,Offshore Support Vessel,2023-09-17T00:49:53.000Z,2023-09-17,103.775980,...,Pasir Panjang Terminal,PPT Maneouvering Zone,522.0,5.00,195.0,230.0,300.0,NaN,NaN,False
675,9888754,563071620,755130,CLS SINGAPORE,2020-07-01,Utility Vessel,Offshore Support Vessel,2023-09-17T00:52:52.000Z,2023-09-17,103.775830,...,Pasir Panjang Terminal,PPT Maneouvering Zone,522.0,5.00,195.0,230.0,300.0,NaN,NaN,False
676,9888754,563071620,755130,CLS SINGAPORE,2020-07-01,Utility Vessel,Offshore Support Vessel,2023-09-17T00:52:53.000Z,2023-09-17,103.775830,...,Pasir Panjang Terminal,PPT Maneouvering Zone,522.0,5.00,195.0,230.0,300.0,NaN,NaN,False
677,9888754,563071620,755130,CLS SINGAPORE,2020-07-01,Utility Vessel,Offshore Support Vessel,2023-09-17T00:55:49.000Z,2023-09-17,103.775830,...,Pasir Panjang Terminal,PPT Maneouvering Zone,522.0,5.00,195.0,230.0,300.0,NaN,NaN,False
678,9888754,563071620,755130,CLS SINGAPORE,2020-07-01,Utility Vessel,Offshore Support Vessel,2023-09-17T00:55:50.000Z,2023-09-17,103.775830,...,Pasir Panjang Terminal,PPT Maneouvering Zone,522.0,5.00,195.0,230.0,300.0,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2822579,7122833,525021052,834377,MAIDEN KITTY,1971-01-01,Tug,Tug Boat,2023-08-21T23:20:59.000Z,2023-08-21,103.762910,...,NaN,NaN,1104.0,11.75,225.0,230.0,300.0,NaN,NaN,False
2822582,9842750,567068500,868221,ATI BHUM,2018-01-01,Deck Cargo Ship,General Cargo,2023-08-21T21:59:34.000Z,2023-08-21,103.763336,...,NaN,NaN,2206.0,10.40,195.0,230.0,300.0,NaN,NaN,False
2822583,9842750,567068500,868221,ATI BHUM,2018-01-01,Deck Cargo Ship,General Cargo,2023-08-21T22:02:34.000Z,2023-08-21,103.768330,...,NaN,NaN,2206.0,10.40,195.0,230.0,300.0,339.0,0.0,False
2822585,9710921,565243000,714758,AYER CHOMEL,2014-10-01,Water Tanker,Chemical Tanker,2023-08-21T21:29:11.000Z,2023-08-21,103.801430,...,NaN,NaN,1640.0,11.00,195.0,230.0,300.0,444.0,362.0,False
2822586,9710921,565243000,714758,AYER CHOMEL,2014-10-01,Water Tanker,Chemical Tanker,2023-08-21T21:29:32.000Z,2023-08-21,103.801430,...,NaN,NaN,1640.0,11.00,195.0,230.0,300.0,444.0,362.0,False

In [29]:
df = df.drop(df.loc[df["vessel_type"]==False].index,axis = 0)
df

,imo,mmsi,vessel_id,vessel_name,date_of_build,vessel_type,group,timestamp,date_only,lon,...,terminal,maneuvering_zone,p,vref,sfc_me,sfc_ae,sfc_ab,ael,abl,require
0,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:01:42.000Z,2023-09-17,103.826065,...,NaN,NaN,7860.0,14.5,185.00,230.0,300.0,507.0,365.0,True
1,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:01:44.000Z,2023-09-17,103.826065,...,NaN,NaN,7860.0,14.5,185.00,230.0,300.0,507.0,365.0,True
2,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:07:43.000Z,2023-09-17,103.825690,...,NaN,NaN,7860.0,14.5,185.00,230.0,300.0,507.0,365.0,True
3,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:07:45.000Z,2023-09-17,103.825690,...,NaN,NaN,7860.0,14.5,185.00,230.0,300.0,507.0,365.0,True
4,9223253,525119038,692017,PRIMA TANGGUH LVI,2002-04-01,Crude/Oil Products Tanker,Crude & Products Tanker,2023-09-17T00:10:42.000Z,2023-09-17,103.825580,...,NaN,NaN,7860.0,14.5,185.00,230.0,300.0,507.0,365.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2822594,9708693,374766000,714547,MSC CLARA,2015-11-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T21:59:17.000Z,2023-08-21,103.761665,...,NaN,PPT Maneouvering Zone,62500.0,19.0,175.00,220.0,300.0,NaN,NaN,True
2822595,9708693,374766000,714547,MSC CLARA,2015-11-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T22:02:17.000Z,2023-08-21,103.761665,...,NaN,PPT Maneouvering Zone,62500.0,19.0,175.00,220.0,300.0,4493.0,908.0,True
2822596,9449106,636020361,647347,MENDELSSOHN,2012-04-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T21:58:47.000Z,2023-08-21,103.783330,...,NaN,PPT Maneouvering Zone,31990.0,23.0,174.83,220.0,300.0,NaN,NaN,True
2822597,9449106,636020361,647347,MENDELSSOHN,2012-04-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T22:01:47.000Z,2023-08-21,103.783330,...,NaN,PPT Maneouvering Zone,31990.0,23.0,174.83,220.0,300.0,2503.0,436.0,True
2822598,9450313,636091832,647462,Northern Priority,2009-10-01,Container Ship (Fully Cellular),Container Ship,2023-08-21T22:01:40.000Z,2023-08-21,103.766670,...,NaN,PPT Maneouvering Zone,36560.0,22.5,172.91,195.0,300.0,NaN,NaN,True

In [31]:
df.to_csv("step3.csv",index = False)